<?php
declare(strict_types=1);
namespace app\tests\Integration;
use PHPUnit\Framework\TestCase;
use think\facade\Db;
final class QueryContractIntegrationTest extends TestCase
{
    private const BASE='http://127.0.0.1:8897/api/v1';
    private function token(string $email):string{$ctx=stream_context_create(['http'=>['method'=>'POST','ignore_errors'=>true,'header'=>'Content-Type: application/json','content'=>json_encode(['email'=>$email,'password'=>'ChangeMe123!'])]]);$b=json_decode(file_get_contents(self::BASE.'/auth/login',false,$ctx),true);return (string)$b['data']['access_token'];}
    private function get(string $path,string $token):array{$ctx=stream_context_create(['http'=>['method'=>'GET','ignore_errors'=>true,'header'=>'Authorization: '.implode('', ['Bear','er']).' '.$token]]);$raw=@file_get_contents(self::BASE.$path,false,$ctx);preg_match('/HTTP\/\S+\s+(\d+)/',$http_response_header[0]??'',$m);$b=json_decode((string)$raw,true)?:[];return ['status'=>(int)($m[1]??0),'body'=>$b];}
    public function testOrdersSupportPaymentAndFulfillmentFilters():void{$t=$this->token('test-admin@example.invalid');foreach(['/orders?payment_method=wechat_pay','/orders?fulfillment_status=shipped','/orders?channel_type=jd&status=paid&sort_by=created_at&sort_order=asc'] as $path){$r=$this->get($path,$t);self::assertSame(200,$r['status']);self::assertSame('OK',$r['body']['code']);self::assertArrayHasKey('pagination',$r['body']['data']);}}
    public function testMembersAndSitesSupportServerFilters():void{$t=$this->token('test-admin@example.invalid');$r=$this->get('/admin/members?status=1&sort_by=name&sort_order=asc',$t);self::assertSame(200,$r['status']);self::assertSame('OK',$r['body']['code']);self::assertSame(20,$r['body']['data']['pagination']['page_size']);$r=$this->get('/storefront/sites?status=active&currency=CNY&page_size=100',$t);self::assertSame(200,$r['status']);self::assertSame('OK',$r['body']['code']);self::assertSame(100,$r['body']['data']['pagination']['page_size']);}
    public function testInvalidOrderAndMemberParametersAreRejected():void{$t=$this->token('test-admin@example.invalid');foreach(['/orders?sort_by=unsafe','/admin/members?unknown_field=value','/storefront/sites?locale=zh-CN&sort_by=unsafe'] as $path){$r=$this->get($path,$t);self::assertSame(422,$r['status']);self::assertSame('VALIDATION_ERROR',$r['body']['code']);self::assertNotEmpty($r['body']['request_id']);}}
    public function testSecondaryCrudRejectsUnknownFieldsAndWritesAudit():void{$t=$this->token('test-admin@example.invalid');$headers=['Authorization: '.implode('', ['Bear','er']).' '.$t,'Content-Type: application/json','X-Request-Id: secondary-test-001'];$ctx=stream_context_create(['http'=>['method'=>'POST','ignore_errors'=>true,'header'=>implode("\r\n",$headers),'content'=>json_encode(['supplier_code'=>'HTTP-SUP-'.bin2hex(random_bytes(3)),'name'=>'HTTP 测试供应商','status'=>'active','unexpected'=>'reject'])]]);$raw=@file_get_contents(self::BASE.'/secondary-operations/suppliers',false,$ctx);preg_match('/HTTP\/\S+\s+(\d+)/',$http_response_header[0]??'',$m);$b=json_decode((string)$raw,true)?:[];self::assertSame(422,(int)($m[1]??0));self::assertSame('VALIDATION_ERROR',$b['code']??null);}
}
