<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ArrowRight, FileText, PackageSearch, Search, ShoppingBag, UserRound, X } from 'lucide-vue-next'; import { useTopbarLayer } from '../../composables/useTopbarLayer'
const router=useRouter(); const {active:activeLayer,open:openLayer,close:closeLayer}=useTopbarLayer(); const open=computed(()=>activeLayer.value==='search'); const query=ref(''); const active=ref(0); const input=ref<HTMLInputElement|null>(null)
const items=[{title:'订单 #EB202609010846',meta:'已付款 · 待揽收',to:'/orders/EB202609010846',type:'订单',icon:ShoppingBag},{title:'Air X Pro 主动降噪耳机',meta:'SPU-286420 · 在售',to:'/products',type:'商品',icon:PackageSearch},{title:'张玥',meta:'黑金会员 · 高价值用户',to:'/users/U-286420',type:'用户',icon:UserRound},{title:'中秋会员专享满减券',meta:'2026-09-10 开始',to:'/coupons',type:'优惠券',icon:FileText},{title:'全渠道经营周报',meta:'今天 08:00 更新',to:'/reports/analysis',type:'报表',icon:FileText}]
const results=computed(()=>{const key=query.value.trim().toLowerCase();return key?items.filter(item=>`${item.title}${item.meta}${item.type}`.toLowerCase().includes(key)):items.slice(0,4)})
function show(){openLayer('search');active.value=0;nextTick(()=>input.value?.focus())} function close(){closeLayer('search');query.value=''} function go(index=active.value){const item=results.value[index];if(item){close();router.push(item.to)}}
function keydown(event:KeyboardEvent){if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();show()}else if(event.key==='Escape'&&open.value)close()}
function navigate(event:KeyboardEvent){if(event.key==='ArrowDown'){event.preventDefault();active.value=(active.value+1)%Math.max(results.value.length,1)}if(event.key==='ArrowUp'){event.preventDefault();active.value=(active.value-1+Math.max(results.value.length,1))%Math.max(results.value.length,1)}if(event.key==='Enter'){event.preventDefault();go()}}
onMounted(()=>document.addEventListener('keydown',keydown));onBeforeUnmount(()=>document.removeEventListener('keydown',keydown))
</script>
<template><button class="global-search" aria-label="打开全局搜索" @click="show"><Search :size="17"/><span>搜索订单、商品或用户...</span><kbd>⌘ K</kbd></button><Teleport to="body"><Transition name="command"><div v-if="open" class="command-overlay" @click.self="close"><section class="command-dialog" role="dialog" aria-modal="true" aria-label="全局搜索"><header><Search :size="18"/><input ref="input" v-model="query" placeholder="搜索订单、商品、用户、优惠券或报表" @keydown="navigate"/><button aria-label="关闭搜索" @click="close"><X :size="17"/></button></header><div class="command-caption"><span>{{query?'搜索结果':'最近访问'}}</span><small>↑↓ 选择 · Enter 打开</small></div><div v-if="results.length" class="command-results"><button v-for="(item,index) in results" :key="item.title" :class="{active:active===index}" @mouseenter="active=index" @click="go(index)"><span><component :is="item.icon" :size="17"/></span><div><strong>{{item.title}}</strong><small>{{item.type}} · {{item.meta}}</small></div><ArrowRight :size="15"/></button></div><div v-else class="command-empty"><Search :size="22"/><strong>没有找到匹配内容</strong><p>尝试输入订单号、商品名称、用户姓名或报表名称。</p></div></section></div></Transition></Teleport></template>
