<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { BookOpen, CircleHelp, ExternalLink, Keyboard, MessageCircleQuestion, Search } from 'lucide-vue-next'; import { useToast } from '../../composables/useToast'; import { useTopbarLayer } from '../../composables/useTopbarLayer'
const router=useRouter(); const {info}=useToast(); const {active,open:openLayer,close}=useTopbarLayer(); const open=computed({get:()=>active.value==='help',set:value=>value?openLayer('help'):close('help')}); const shortcuts=ref(false); const query=ref(''); const root=ref<HTMLElement|null>(null)
const matches=computed(()=>({guide:'使用指南订单商品渠道'.includes(query.value),keys:'键盘快捷键效率'.includes(query.value),support:'联系系统管理员权限账号业务'.includes(query.value)}))
function guide(){close('help');router.push('/features')} function support(){info('管理员联系方式','请发送邮件至 admin@ebase.cn');close('help')}
function outside(event:MouseEvent){if(open.value&&root.value&&!root.value.contains(event.target as Node))close('help')} function key(event:KeyboardEvent){if(event.key==='Escape')close('help')}
onMounted(()=>{document.addEventListener('click',outside);document.addEventListener('keydown',key)});onBeforeUnmount(()=>{document.removeEventListener('click',outside);document.removeEventListener('keydown',key)})
</script>
<template><div ref="root" class="topbar-popover-wrap"><button :class="{active:open}" aria-label="帮助" aria-haspopup="dialog" :aria-expanded="open" @click="open=!open"><CircleHelp :size="19"/></button><Transition name="topbar-popover"><section v-if="open" class="topbar-popover help-popover"><header><div><strong>帮助与支持</strong><span>查找文档或联系管理员</span></div></header><label><Search :size="15"/><input v-model="query" placeholder="搜索帮助内容"/></label><nav v-if="!shortcuts"><button v-if="matches.guide" @click="guide"><BookOpen :size="17"/><span><b>使用指南</b><small>了解订单、商品和渠道操作</small></span><ExternalLink :size="14"/></button><button v-if="matches.keys" @click="shortcuts=true"><Keyboard :size="17"/><span><b>键盘快捷键</b><small>提高后台日常操作效率</small></span><span class="help-key">⌘ K</span></button><button v-if="matches.support" @click="support"><MessageCircleQuestion :size="17"/><span><b>联系系统管理员</b><small>权限、账号和业务问题</small></span><ExternalLink :size="14"/></button></nav><div v-else class="shortcut-list"><button @click="shortcuts=false">返回帮助</button><div><span>全局搜索</span><kbd>⌘ K</kbd></div><div><span>关闭弹层</span><kbd>Esc</kbd></div><div><span>选择结果</span><kbd>↑ ↓ Enter</kbd></div></div><footer>系统版本 v0.1.0 · <button @click="info('当前已是最新版本','暂无待安装的后台更新')">查看更新记录</button></footer></section></Transition></div></template>
