CREATE TABLE IF NOT EXISTS `channel_products` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `channel_store_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `external_product_id` VARCHAR(128) NOT NULL,
  `merchant_product_code` VARCHAR(128) NULL,
  `title` VARCHAR(255) NULL,
  `category_id` VARCHAR(128) NULL,
  `category_name` VARCHAR(255) NULL,
  `listing_status` VARCHAR(24) NOT NULL DEFAULT 'draft',
  `sync_status` VARCHAR(24) NOT NULL DEFAULT 'pending',
  `platform_payload` JSON NULL,
  `last_synced_at` DATETIME NULL,
  `last_sync_error_code` VARCHAR(64) NULL,
  `last_sync_error` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_channel_product_external` (`channel_store_id`, `external_product_id`),
  UNIQUE KEY `uk_channel_product_internal` (`channel_store_id`, `product_id`),
  KEY `idx_channel_product_product_status` (`product_id`, `listing_status`),
  KEY `idx_channel_product_store_sync` (`channel_store_id`, `sync_status`),
  CONSTRAINT `fk_channel_product_store` FOREIGN KEY (`channel_store_id`) REFERENCES `channel_stores` (`id`),
  CONSTRAINT `fk_channel_product_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台商品映射';
