CREATE TABLE IF NOT EXISTS `channel_product_skus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `channel_product_id` BIGINT UNSIGNED NOT NULL,
  `product_sku_id` BIGINT UNSIGNED NOT NULL,
  `external_sku_id` VARCHAR(128) NOT NULL,
  `merchant_sku_code` VARCHAR(128) NULL,
  `spec_snapshot` JSON NULL,
  `channel_price` DECIMAL(12,2) NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'CNY',
  `inventory_policy` VARCHAR(24) NOT NULL DEFAULT 'shared',
  `allocated_quantity` INT UNSIGNED NULL,
  `listing_status` VARCHAR(24) NOT NULL DEFAULT 'draft',
  `sync_status` VARCHAR(24) NOT NULL DEFAULT 'pending',
  `last_inventory_synced_at` DATETIME NULL,
  `last_price_synced_at` DATETIME NULL,
  `last_sync_error_code` VARCHAR(64) NULL,
  `last_sync_error` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_channel_sku_external` (`channel_product_id`, `external_sku_id`),
  UNIQUE KEY `uk_channel_sku_internal` (`channel_product_id`, `product_sku_id`),
  KEY `idx_channel_sku_internal` (`product_sku_id`),
  KEY `idx_channel_sku_sync` (`sync_status`, `updated_at`),
  CONSTRAINT `fk_channel_sku_product` FOREIGN KEY (`channel_product_id`) REFERENCES `channel_products` (`id`),
  CONSTRAINT `fk_channel_sku_internal` FOREIGN KEY (`product_sku_id`) REFERENCES `product_skus` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台 SKU 映射';
