CREATE TABLE IF NOT EXISTS `channel_order_item_exceptions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `channel_store_id` BIGINT UNSIGNED NULL,
  `external_order_item_id` VARCHAR(128) NULL,
  `external_order_item_key` VARCHAR(191) NOT NULL,
  `external_product_id` VARCHAR(128) NULL,
  `external_sku_id` VARCHAR(128) NULL,
  `merchant_sku_code` VARCHAR(128) NULL,
  `reason_code` VARCHAR(64) NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'pending',
  `raw_item` JSON NOT NULL,
  `resolved_product_sku_id` BIGINT UNSIGNED NULL,
  `resolved_by` BIGINT UNSIGNED NULL,
  `resolved_at` DATETIME NULL,
  `resolution_note` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_item_exception_key` (`order_id`, `external_order_item_key`),
  KEY `idx_exception_status` (`status`, `created_at`),
  KEY `idx_exception_store` (`channel_store_id`, `status`),
  KEY `idx_exception_external_sku` (`external_sku_id`, `status`),
  KEY `idx_exception_order` (`order_id`),
  KEY `idx_exception_resolved_sku` (`resolved_product_sku_id`),
  CONSTRAINT `fk_exception_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`),
  CONSTRAINT `fk_exception_store` FOREIGN KEY (`channel_store_id`) REFERENCES `channel_stores` (`id`),
  CONSTRAINT `fk_exception_sku` FOREIGN KEY (`resolved_product_sku_id`) REFERENCES `product_skus` (`id`),
  CONSTRAINT `fk_exception_member` FOREIGN KEY (`resolved_by`) REFERENCES `members` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='渠道订单商品映射异常';
