<?php
declare (strict_types=1);
namespace app\common\service;
use app\common\exception\BusinessException;
use think\facade\Db;
class FulfillmentService
{
 public function create(int $orderId,array $data,?int $operatorId): array {return Db::transaction(function()use($orderId,$data,$operatorId){$order=Db::name('orders')->where('id',$orderId)->lock(true)->find();if(!$order)throw BusinessException::notFound('订单不存在');if(!in_array($order['status'],['paid','processing'],true))throw new BusinessException('ORDER_STATE_INVALID','仅已付款或处理中订单可创建履约单',409);$now=date('Y-m-d H:i:s');$id=Db::name('fulfillments')->insertGetId(['fulfillment_no'=>'EF'.date('YmdHis').strtoupper(bin2hex(random_bytes(3))),'order_id'=>$orderId,'warehouse_code'=>$data['warehouse_code']??null,'status'=>'processing','recipient_snapshot'=>json_encode($data['recipient_snapshot'],JSON_UNESCAPED_UNICODE),'shipping_method'=>$data['shipping_method']??null,'created_at'=>$now,'updated_at'=>$now]);Db::name('orders')->where('id',$orderId)->update(['status'=>'processing','updated_at'=>$now]);return Db::name('fulfillments')->where('id',$id)->find();});}
 public function ship(int $fulfillmentId,array $data,?int $operatorId): array{return Db::transaction(function()use($fulfillmentId,$data,$operatorId){$f=Db::name('fulfillments')->where('id',$fulfillmentId)->lock(true)->find();if(!$f)throw BusinessException::notFound('履约单不存在');if($f['status']!=='processing')throw new BusinessException('ORDER_STATE_INVALID','当前履约单不能发货',409);$now=date('Y-m-d H:i:s');$packageId=Db::name('shipment_packages')->insertGetId(['fulfillment_id'=>$fulfillmentId,'package_no'=>'EP'.date('YmdHis').strtoupper(bin2hex(random_bytes(3))),'carrier_code'=>$data['carrier_code'],'tracking_no'=>$data['tracking_no'],'status'=>'shipped','carrier_payload'=>isset($data['carrier_payload'])?json_encode($data['carrier_payload'],JSON_UNESCAPED_UNICODE):null,'shipped_at'=>$now,'created_at'=>$now,'updated_at'=>$now]);Db::name('fulfillments')->where('id',$fulfillmentId)->update(['status'=>'shipped','shipped_at'=>$now,'updated_at'=>$now]);Db::name('orders')->where('id',$f['order_id'])->update(['status'=>'shipped','updated_at'=>$now]);Db::name('order_status_logs')->insert(['order_id'=>$f['order_id'],'from_status'=>'processing','to_status'=>'shipped','operator_id'=>$operatorId,'source'=>'fulfillment','remark'=>'履约发货','created_at'=>$now]);return Db::name('shipment_packages')->where('id',$packageId)->find();});}
 public function addTrackingEvent(int $packageId,array $data): array {$p=Db::name('shipment_packages')->where('id',$packageId)->find();if(!$p)throw BusinessException::notFound('包裹不存在');$id=Db::name('shipment_tracking_events')->insertGetId(['package_id'=>$packageId,'event_code'=>$data['event_code']??null,'event_status'=>$data['event_status'],'description'=>$data['description'],'location'=>$data['location']??null,'occurred_at'=>$data['occurred_at']??date('Y-m-d H:i:s'),'raw_payload'=>isset($data['raw_payload'])?json_encode($data['raw_payload'],JSON_UNESCAPED_UNICODE):null,'created_at'=>date('Y-m-d H:i:s')]);return Db::name('shipment_tracking_events')->where('id',$id)->find();}
}
