<?php
declare(strict_types=1);
namespace app\controller;
use app\common\controller\ApiController;use app\common\service\NotificationService;use app\common\exception\BusinessException;use think\facade\Db;use think\Request;use think\Response;
final class LogisticsExceptionController extends ApiController
{
 public function index(Request $request):Response{$q=Db::name('logistics_exceptions');if($status=$request->get('status'))$q->where('status',$status);$items=$q->order('id','desc')->paginate(['list_rows'=>100,'page'=>(int)$request->get('page',1)]);return $this->success($items);}
 public function detect():Response{$now=time();$packages=Db::name('shipment_packages')->where('status','shipped')->select();$created=0;foreach($packages as $p){$days=(int)floor(($now-strtotime($p['shipped_at']??$p['created_at']))/86400);if($days<3)continue;$exists=Db::name('logistics_exceptions')->where('package_id',$p['id'])->where('exception_type','stalled')->whereIn('status',['open','processing'])->find();if($exists)continue;$id=Db::name('logistics_exceptions')->insertGetId(['package_id'=>$p['id'],'exception_type'=>'stalled','severity'=>$days>=7?'high':'medium','status'=>'open','description'=>"包裹 {$p['tracking_no']} 已 {$days} 天无新轨迹",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);(new NotificationService())->broadcast('logistics_exception','物流异常待处理',"包裹 {$p['tracking_no']} 已 {$days} 天无新轨迹",'/logistics',['exception_id'=>$id,'package_id'=>$p['id']]);$created++;}return $this->success(['created'=>$created],'物流异常检测完成');}
 public function update(Request $request,int $id):Response{$this->validate($request->post(),['status'=>'require|in:open,processing,resolved,ignored','description'=>'max:500']);$e=Db::name('logistics_exceptions')->where('id',$id)->find();if(!$e)throw BusinessException::notFound('物流异常不存在');$status=$request->post('status');Db::name('logistics_exceptions')->where('id',$id)->update(['status'=>$status,'description'=>$request->post('description',$e['description']),'assigned_to'=>$this->requireMember()->id,'resolved_at'=>in_array($status,['resolved','ignored'])?date('Y-m-d H:i:s'):null,'updated_at'=>date('Y-m-d H:i:s')]);return $this->success(null,'物流异常状态已更新');}
}
