<?php
declare (strict_types=1);
namespace app\controller;
use app\common\controller\ApiController;use app\common\exception\BusinessException;use app\common\model\Member;use app\validate\MemberAdminValidate;use think\facade\Cache;use think\facade\Db;use think\Request;use think\Response;
class MemberAdminController extends ApiController
{
 public function index(Request $request):Response{$page=max(1,(int)$request->get('page',1));$size=min(100,max(1,(int)$request->get('page_size',20)));$q=Member::with('roles');if($keyword=trim((string)$request->get('keyword','')))$q->whereLike('name|email','%'.addcslashes($keyword,'%_').'%');if(($status=$request->get('status'))!==null&&$status!=='')$q->where('status',(int)$status);$total=$q->count();return $this->paginated($q->order('id','desc')->page($page,$size)->select(),$page,$size,$total);}
 public function read(int $id):Response{$m=Member::with('roles')->find($id);if(!$m)throw BusinessException::notFound('成员不存在');return $this->success($m);}
 public function invite(Request $request):Response{$this->validate($request->post(),MemberAdminValidate::class);$data=$request->post();if(Member::where('email',$data['email'])->find())throw new BusinessException('RESOURCE_CONFLICT','该邮箱已存在',409);$temporaryPassword=bin2hex(random_bytes(12));$member=Db::transaction(function()use($data,$temporaryPassword){$id=Db::name('members')->insertGetId(['email'=>$data['email'],'name'=>$data['name'],'password_hash'=>password_hash($temporaryPassword,PASSWORD_DEFAULT),'status'=>1,'is_super'=>0,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);foreach($data['role_ids']??[] as $roleId)Db::name('member_roles')->insert(['member_id'=>$id,'role_id'=>$roleId,'created_at'=>date('Y-m-d H:i:s')]);return Member::find($id);});$token=bin2hex(random_bytes(24));Cache::store('redis')->set('auth:invite:'.$token,json_encode(['member_id'=>$member->id]),86400);return $this->success(['member'=>$member,'invite_token'=>$token,'expires_in'=>86400],'成员已邀请',201);}
 public function update(Request $request,int $id):Response{$m=Member::find($id);if(!$m)throw BusinessException::notFound('成员不存在');$data=$request->post();$this->validate(array_merge($m->toArray(),$data),MemberAdminValidate::class);Db::transaction(function()use($m,$data){$update=[];foreach(['name','email','status']as$key)if(array_key_exists($key,$data))$update[$key]=$data[$key];if($update)$m->save($update);if(array_key_exists('role_ids',$data)){Db::name('member_roles')->where('member_id',$m->id)->delete();foreach(array_unique($data['role_ids'])as$roleId)Db::name('member_roles')->insert(['member_id'=>$m->id,'role_id'=>$roleId,'created_at'=>date('Y-m-d H:i:s')]);}});Cache::store('redis')->delete('perm:member:'.$id);return $this->success(Member::with('roles')->find($id),'成员已更新');}
 public function disable(int $id):Response{$m=Member::find($id);if(!$m)throw BusinessException::notFound('成员不存在');if($m->is_super)throw new BusinessException('RESOURCE_CONFLICT','不能停用超级管理员',409);$m->save(['status'=>0]);Db::name('member_sessions')->where('member_id',$id)->whereNull('revoked_at')->update(['revoked_at'=>date('Y-m-d H:i:s')]);Cache::store('redis')->delete('perm:member:'.$id);return $this->success(null,'成员已停用，所有会话已撤销');}
 public function resetPassword(int $id):Response{$m=Member::find($id);if(!$m)throw BusinessException::notFound('成员不存在');$token=bin2hex(random_bytes(24));Cache::store('redis')->set('auth:password-reset:'.$token,json_encode(['member_id'=>$id]),1800);return $this->success(['reset_token'=>$token,'expires_in'=>1800],'密码重置令牌已生成');}
}
