<?php
declare(strict_types=1);
namespace app\controller;
use app\common\controller\ApiController;use app\common\service\NotificationService;use app\common\exception\BusinessException;use think\facade\Db;use think\Request;use think\Response;
final class RestockController extends ApiController
{
 public function suggestions():Response{$days=30;$rows=Db::query("SELECT s.id,s.sku_code,s.name,s.stock_quantity,s.reserved_quantity,s.price,COALESCE(SUM(CASE WHEN o.created_at >= DATE_SUB(NOW(),INTERVAL 30 DAY) AND o.status NOT IN ('cancelled') THEN oi.quantity ELSE 0 END),0) AS sold_30d FROM product_skus s LEFT JOIN order_items oi ON oi.sku_id=s.id LEFT JOIN orders o ON o.id=oi.order_id WHERE s.status='active' GROUP BY s.id ORDER BY (s.stock_quantity-s.reserved_quantity) ASC");$items=[];foreach($rows as $row){$daily=round((float)$row['sold_30d']/$days,2);$lead=7;$safety=(int)ceil($daily*3);$target=(int)ceil($daily*($lead+14)+$safety);$available=(int)$row['stock_quantity']-(int)$row['reserved_quantity'];$suggest=max(0,$target-$available);if($suggest>0)$items[]=[...$row,'daily_sales'=>$daily,'lead_days'=>$lead,'safety_stock'=>$safety,'suggested_quantity'=>$suggest,'estimated_amount'=>bcmul((string)$row['price'],(string)$suggest,2)];}return $this->success($items);}
 public function create(Request $request):Response{$this->validate($request->post(),['name'=>'require|max:160','items'=>'require|array|min:1','warehouse_code'=>'max:64','expected_at'=>'dateFormat:Y-m-d H:i:s']);$d=$request->post();$member=$this->requireMember();return Db::transaction(function()use($d,$member){$now=date('Y-m-d H:i:s');$planId=Db::name('restock_plans')->insertGetId(['plan_no'=>'RP'.date('YmdHis').strtoupper(bin2hex(random_bytes(3))),'name'=>$d['name'],'warehouse_code'=>$d['warehouse_code']??null,'status'=>'pending_approval','suggested_quantity'=>0,'estimated_amount'=>0,'expected_at'=>$d['expected_at']??null,'created_by'=>$member->id,'created_at'=>$now,'updated_at'=>$now]);$totalQty=0;$totalAmount='0.00';foreach($d['items'] as $item){$sku=Db::name('product_skus')->where('id',(int)$item['sku_id'])->find();if(!$sku)throw BusinessException::notFound('SKU 不存在');$qty=(int)$item['quantity'];$amount=bcmul((string)$sku['price'],(string)$qty,2);Db::name('restock_plan_items')->insert(['plan_id'=>$planId,'sku_id'=>$sku['id'],'current_stock'=>$sku['stock_quantity'],'reserved_stock'=>$sku['reserved_quantity'],'daily_sales'=>$item['daily_sales']??0,'lead_days'=>$item['lead_days']??7,'safety_stock'=>$item['safety_stock']??0,'suggested_quantity'=>$qty,'unit_price'=>$sku['price']]);$totalQty+=$qty;$totalAmount=bcadd($totalAmount,$amount,2);}Db::name('restock_plans')->where('id',$planId)->update(['suggested_quantity'=>$totalQty,'estimated_amount'=>$totalAmount,'updated_at'=>$now]);(new NotificationService())->broadcast('restock','补货计划待审批',"补货计划 {$d['name']} 共 {$totalQty} 件，预计金额 ¥{$totalAmount}",'/inventory/restock',['plan_id'=>$planId]);return $this->success(Db::name('restock_plans')->where('id',$planId)->find(),'补货计划已创建并通知审批人',201);});}
}
