<script setup lang="ts">
import { computed, onBeforeUnmount, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowRight, Download, MoreHorizontal, Plus, RefreshCw, Search } from 'lucide-vue-next'
import { getOrder, listOrders, type Order, type OrderDetail } from '../api/orders'
import { getDashboardStats, listOperationModule } from '../api/operations'
import { ApiError } from '../api/client'
import { useToast } from '../composables/useToast'
import { moduleConfigs } from '../data/moduleConfigs'
import TableState from '../components/common/TableState.vue'
import DateRangePicker, { type DateRangeValue } from '../components/common/DateRangePicker.vue'
import ToolbarSelect, { type ToolbarSelectOption } from '../components/common/ToolbarSelect.vue'
const props=defineProps<{title:string}>()
const route=useRoute()
const router=useRouter()
const { success, error: showError, info }=useToast()
const query=ref(String(route.query.order_no||'')); const activeTab=ref(0); const selectedRow=ref(0); const selected=ref<number[]>([])
const reportDates=ref<DateRangeValue>({start:'2026-08-04',end:'2026-09-02',preset:30})
const filterValues=reactive<Record<string,string>>({})
const channelOptions:ToolbarSelectOption[]=[{label:'全部渠道',value:''},{label:'独立站',value:'storefront'},{label:'天猫',value:'tmall'},{label:'京东',value:'jd'},{label:'抖音',value:'douyin'},{label:'品牌小程序',value:'wechat_miniapp'}]
const config=computed(()=>moduleConfigs[props.title])
const paths:Record<string,{primary:string;detail:string}>={'订单管理':{primary:'/orders/new',detail:'/orders/EB202609010846'},'物流履约':{primary:'/logistics/SF128604780',detail:'/logistics/SF128604780'},'产品管理':{primary:'/products/new',detail:'/products/new'},'库存中心':{primary:'/inventory/restock',detail:'/inventory/restock'},'用户管理':{primary:'/users/U-286420',detail:'/users/U-286420'},'内容中心':{primary:'/content/new',detail:'/content/new'},'优惠券管理':{primary:'/coupons/new',detail:'/coupons/new'},'营销活动':{primary:'/marketing/new',detail:'/marketing/new'},'数据报表':{primary:'/reports/analysis',detail:'/reports/analysis'},'权限与系统设置':{primary:'/settings/roles/operator',detail:'/settings/roles/operator'}}
const workflow=computed(()=>paths[props.title])
const remoteOrders=ref<Order[]>([]); const orderTotal=ref(0); const orderPages=ref(1); const page=ref(1); const pageSize=20; const loading=ref(false); const loadError=ref('')
const selectedOrderId=ref(''); const selectedOrderDetail=ref<OrderDetail|null>(null); const detailLoading=ref(false); const channel=ref(''); const storeId=ref('')
const isOrders=computed(()=>props.title==='订单管理')
const orderTabs=[{label:'全部订单',status:''},{label:'待付款',status:'pending_payment'},{label:'待发货',status:'paid'},{label:'处理中',status:'processing'},{label:'运输中',status:'shipped'},{label:'已完成',status:'completed'},{label:'已取消',status:'cancelled'}]
const orderTabCounts=ref<Record<string,number>>({})
const currentTabs=computed(()=>isOrders.value?orderTabs.map(item=>item.label):config.value.tabs)
const currentTabCounts=computed(()=>isOrders.value?orderTabs.map(item=>orderTabCounts.value[item.status]??0):config.value.tabCounts)
const activeOrderStatus=computed(()=>isOrders.value?orderTabs[activeTab.value]?.status||'':'')
function formatCount(value: string | number | undefined): string {
  const numeric = Number(String(value ?? '').replace(/,/g, ''))
  return Number.isFinite(numeric) ? numeric.toLocaleString('zh-CN') : '0'
}
function displayOrderStatus(status:string){return ({pending_payment:'待付款',paid:'待发货',processing:'处理中',shipped:'运输中',completed:'已完成',cancelled:'已取消'} as Record<string,string>)[status]||status}
function displayChannel(channel:string){return ({storefront:'独立站',tmall:'天猫',jd:'京东',douyin:'抖音',wechat_miniapp:'品牌小程序'} as Record<string,string>)[channel]||channel}
function displayPayment(channel=''){return ({wechat:'微信支付',alipay:'支付宝',wechat_pay:'微信支付'} as Record<string,string>)[channel]||channel||'暂无支付记录'}
function formatTime(value?:string|null){if(!value)return '—';return new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))}
const remoteRows=ref<Array<Record<string, unknown>>>([])
const moduleTotal=ref(0)
const moduleKey:Record<string,string>={'产品管理':'products','库存中心':'inventory','用户管理':'customers','物流履约':'logistics','内容中心':'content','优惠券管理':'coupons','营销活动':'campaigns'}
const moduleColumns:Record<string,string[]>={'products':['product_no','name','brand','min_price','sku_count','available_stock','published_channels','status'],'inventory':['sku_code','product_name','sku_name','stock_quantity','reserved_quantity','available_stock','price','status'],'customers':['customer_no','name','tags','source_channel','order_count','total_spend','last_order_at'],'logistics':['package_no','tracking_no','carrier_code','order_id','status','exception_type','severity','description'],'content':['id','title','content_type','slug','status','published_at','updated_at'],'coupons':['code','name','discount_type','discount_value','min_amount','total_quantity','claimed_quantity','status'],'campaigns':['id','name','campaign_type','budget','status','starts_at','ends_at']}
async function loadModuleRows(){if(isOrders.value||!moduleKey[props.title])return;loading.value=true;loadError.value='';try{const data=await listOperationModule(moduleKey[props.title],{page:1,page_size:100,keyword:query.value});remoteRows.value=data.items;moduleTotal.value=data.pagination.total}catch(e){loadError.value=e instanceof ApiError?e.body.message:'数据加载失败'}finally{loading.value=false}}
function displayStatus(value: unknown): string { return ({ active: '在售', draft: '草稿', archived: '已归档', pending: '待处理', processing: '处理中', shipped: '运输中', delivered: '已签收', open: '异常待处理', disabled: '已停用' } as Record<string, string>)[String(value)] || String(value ?? '—') }
function customerTier(value: unknown): string { const amount=Number(value||0); return amount>=50000?'黑金会员':amount>=20000?'金卡会员':amount>=5000?'银卡会员':'普通会员' }
function moduleRow(item: Record<string, unknown>): string[] {
  if (moduleKey[props.title] === 'products') return [String(item.product_no ?? '—'), String(item.name ?? '—'), String(item.brand ?? '—'), `¥${item.min_price ?? 0}–${item.max_price ?? 0}`, formatCount(Number(item.sku_count)), formatCount(Number(item.available_stock)), `${formatCount(Number(item.published_channels))} 个渠道`, displayStatus(item.status),]
  if (moduleKey[props.title] === 'inventory') return [String(item.sku_code ?? '—'), String(item.product_name ?? '—'), String(item.sku_name ?? '—'), formatCount(Number(item.stock_quantity)), formatCount(Number(item.reserved_quantity)), formatCount(Number(item.available_stock)), `¥${item.price ?? 0}`, displayStatus(item.status)]
  if (moduleKey[props.title] === 'customers') return [String(item.customer_no ?? '—'), String(item.name ?? '—'), customerTier(item.total_spend), String(item.tags || '未打标签'), displayChannel(String(item.source_channel ?? '')), formatCount(Number(item.order_count)), `¥${item.total_spend ?? 0}`, formatTime(String(item.last_order_at ?? ''))]
  if (moduleKey[props.title] === 'logistics') return [String(item.package_no ?? '—'), String(item.tracking_no ?? '—'), String(item.carrier_code ?? '—'), String(item.order_id ?? '—'), displayStatus(item.status), String(item.exception_type ?? '—'), String(item.severity ?? '—'), String(item.description ?? '—')]
  return moduleColumns[moduleKey[props.title]].map(key => String(item[key] ?? '—'))
}
function filteredStaticRows(){const k=query.value.trim().toLowerCase();const tab=config.value.tabs[activeTab.value];let result=config.value.rows;if(activeTab.value>0)result=result.filter(r=>r.some(v=>String(v).includes(tab)||tab.includes(String(v))));return k?result.filter(r=>r.some(v=>String(v).toLowerCase().includes(k))):result}
const allSelected=computed(()=>rows.value.length>0&&selected.value.length===rows.value.length)
const displayMetrics=computed(()=>{const key=moduleKey[props.title];const rows=remoteRows.value;if(key==='products')return [{label:'商品总数',value:formatCount(moduleTotal.value),note:'数据库真实数据'},{label:'当前页 SKU',value:formatCount(rows.reduce((sum,item)=>sum+Number(item.sku_count||0),0)),note:'当前页聚合'},{label:'可售库存',value:formatCount(rows.reduce((sum,item)=>sum+Number(item.available_stock||0),0)),note:'当前页聚合'},{label:'已发布渠道',value:formatCount(rows.reduce((sum,item)=>sum+Number(item.published_channels||0),0)),note:'当前页聚合'}];if(key==='inventory')return [{label:'SKU 总数',value:formatCount(moduleTotal.value),note:'数据库真实数据'},{label:'现货',value:formatCount(rows.reduce((sum,item)=>sum+Number(item.stock_quantity||0),0)),note:'当前页聚合'},{label:'锁定',value:formatCount(rows.reduce((sum,item)=>sum+Number(item.reserved_quantity||0),0)),note:'当前页聚合'},{label:'可售',value:formatCount(rows.reduce((sum,item)=>sum+Number(item.available_stock||0),0)),note:'当前页聚合'}];if(key==='customers')return [{label:'消费者总数',value:formatCount(moduleTotal.value),note:'数据库真实数据'},{label:'当前页启用',value:formatCount(rows.filter(item=>item.status==='active').length),note:'当前页统计'},{label:'当前页来源',value:String(new Set(rows.map(item=>item.source_channel)).size),note:'渠道数'},{label:'当前页加载',value:formatCount(rows.length),note:'本页记录'}];if(key==='logistics')return [{label:'包裹总数',value:formatCount(moduleTotal.value),note:'数据库真实数据'},{label:'异常包裹',value:formatCount(rows.filter(item=>item.exception_type&&item.exception_type!=='—').length),note:'当前页统计'},{label:'运输中',value:formatCount(rows.filter(item=>item.status==='shipped').length),note:'当前页统计'},{label:'当前页加载',value:formatCount(rows.length),note:'本页记录'}];return config.value.metrics})
const rows=computed(()=>{if(isOrders.value)return remoteOrders.value.map(order=>[order.order_no,order.external_order_no||'后台订单',`${order.items?.[0]?.product_name||'订单商品'} · ${order.items?.[0]?.quantity||0} 件`,displayChannel(order.channel_type||'storefront'),`${order.currency} ${order.total_amount}`,'—',displayOrderStatus(order.status),order.created_at]);if(moduleKey[props.title])return remoteRows.value.map(moduleRow);return filteredStaticRows()})
let requestSequence=0
async function loadOrderCounts(){try{const results=await Promise.all(orderTabs.map(item=>listOrders({page:1,page_size:1,status:item.status||undefined})));orderTabCounts.value=Object.fromEntries(orderTabs.map((item,index)=>[item.status,results[index].pagination.total]))}catch{/* 列表错误态已承担主要反馈，统计失败不阻塞列表。 */}}
async function loadOrderDetail(id:string){if(!id){selectedOrderDetail.value=null;return}detailLoading.value=true;try{selectedOrderDetail.value=await getOrder(id)}catch(e){showError('订单详情加载失败',e instanceof ApiError?e.body.message:'请稍后重试')}finally{detailLoading.value=false}}
async function loadOrders(){const sequence=++requestSequence;loading.value=true;loadError.value='';selected.value=[];try{const data=await listOrders({page:page.value,page_size:pageSize,order_no:query.value,status:activeOrderStatus.value||undefined,channel_type:channel.value||undefined,channel_store_id:storeId.value||undefined});if(sequence!==requestSequence)return;remoteOrders.value=data.items;orderTotal.value=data.pagination.total;orderPages.value=Math.max(1,data.pagination.pages);const nextId=data.items.some(item=>item.id===selectedOrderId.value)?selectedOrderId.value:data.items[0]?.id||'';selectedOrderId.value=nextId;selectedRow.value=Math.max(0,data.items.findIndex(item=>item.id===nextId));await loadOrderDetail(nextId)}catch(e){if(sequence!==requestSequence)return;loadError.value=e instanceof ApiError?e.body.message:'订单加载失败';remoteOrders.value=[];selectedOrderDetail.value=null}finally{if(sequence===requestSequence)loading.value=false}}
function toggleAll(){selected.value=allSelected.value?[]:rows.value.map((_,i)=>i)}
function openOrder(order:Order){router.push(`/orders/${order.id}`)}
function exportData(){info('导出任务未创建','当前后端尚未提供订单导出接口。')}
function changeReportDates(value:DateRangeValue){info('报表周期已更新',`${value.start} 至 ${value.end}`)}
function toolbarOptions(label:string):ToolbarSelectOption[]{let values=[label];if(label.includes('渠道'))values=[label,'独立站','天猫','京东','抖音'];else if(label.includes('店铺'))values=[label,'天猫旗舰店','京东自营店','抖音商城','品牌小程序'];else if(label.includes('仓库'))values=[label,'华东一号仓','华南一号仓','华北二号仓'];else if(label.includes('状态'))values=[label,'正常','待处理','已完成','已停用'];else if(label.includes('类目'))values=[label,'数码影音','家用电器','家居办公'];else if(label.includes('品牌'))values=[label,'Apple','Dyson','EBASE'];else if(label.includes('负责人'))values=[label,'林知夏','周宁','陈曦'];else values=[label,'不限','需要关注'];return values.map(value=>({label:value,value}))}
function changeToolbarFilter(label:string,value:string){filterValues[label]=value;info('筛选条件已更新',`${label}：${value}`)}
function selectOrder(index:number){selectedRow.value=index;selectedOrderId.value=remoteOrders.value[index]?.id||'';void loadOrderDetail(selectedOrderId.value)}
function goPage(target:number){if(target<1||target>orderPages.value||target===page.value)return;page.value=target}
const visiblePages=computed(()=>{const start=Math.max(1,Math.min(page.value-1,orderPages.value-2));return Array.from({length:Math.min(3,orderPages.value)},(_,index)=>start+index)})
const orderMetrics=computed(()=>[{label:'订单总量',value:orderTabCounts.value['']??orderTotal.value,note:'来自订单 API'},{label:'待发货',value:orderTabCounts.value.paid??0,note:'等待仓库处理'},{label:'运输中',value:orderTabCounts.value.shipped??0,note:'正在履约'},{label:'当前页金额',value:`CNY ${remoteOrders.value.reduce((sum,item)=>sum+Number(item.total_amount||0),0).toFixed(2)}`,note:`本页 ${remoteOrders.value.length} 单`}])
const contextOrder=computed(()=>selectedOrderDetail.value||remoteOrders.value.find(item=>item.id===selectedOrderId.value)||null)
const fulfillmentProgress=computed(()=>({pending_payment:12,paid:30,processing:52,shipped:76,completed:100,cancelled:0} as Record<string,number>)[contextOrder.value?.status||'']??0)
const contextItems=computed(()=>{const order=selectedOrderDetail.value;if(!order)return[];const payment=order.payments?.[0];const fulfillment=order.fulfillments?.[0];const log=order.status_logs?.at(-1);return[{title:payment?.status==='paid'?'支付已确认':'支付状态',meta:payment?`${displayPayment(payment.channel)} · ${payment.currency} ${payment.amount}`:'暂无支付记录',tone:payment?.status==='paid'?'success':'warning'},{title:fulfillment?'履约任务已创建':'等待创建履约',meta:fulfillment?`${fulfillment.warehouse_code||'未分配仓库'} · ${displayOrderStatus(fulfillment.status)}`:'订单付款后进入履约',tone:fulfillment?'primary':'warning'},{title:'当前订单状态',meta:`${displayOrderStatus(order.status)} · ${formatTime(order.updated_at)}`,tone:order.status==='cancelled'?'danger':'primary'},{title:'最近状态记录',meta:log?`${displayOrderStatus(log.to_status)} · ${formatTime(log.created_at)}`:'暂无状态变更记录',tone:'primary'}]})
let searchTimer:number|undefined
watch(query,()=>{if(isOrders.value){window.clearTimeout(searchTimer);searchTimer=window.setTimeout(()=>{page.value=1;void loadOrders()},280)}else void loadModuleRows()})
watch([activeTab,channel,storeId],()=>{if(isOrders.value){page.value=1;void loadOrders()}else void loadModuleRows()})
watch(page,()=>{if(isOrders.value)void loadOrders()})
watch(isOrders,value=>{if(value){void loadOrderCounts();void loadOrders()}else void loadModuleRows()},{immediate:true})
onBeforeUnmount(()=>window.clearTimeout(searchTimer))
</script>
<template><section v-if="config" class="data-page">
<div class="page-heading"><div><span class="eyebrow">{{config.eyebrow}}</span><h1>{{title}}</h1><p>{{config.description}}</p></div><div class="heading-actions"><button class="button secondary" @click="exportData"><Download :size="16"/>导出</button><button class="button primary" @click="router.push(workflow.primary)"><Plus :size="16"/>{{config.primaryAction}}</button></div></div>
<section class="metric-strip module-metrics"><article v-for="m in (isOrders?orderMetrics:(moduleKey[title]?displayMetrics:config.metrics))" :key="m.label" class="metric-item"><span>{{m.label}}</span><strong>{{m.value}}</strong><small><template v-if="'delta' in m"><b :class="{negative:'negative' in m && m.negative}">{{m.delta}}</b></template>{{m.note}}</small></article></section>
<div class="module-tabs"><button v-for="(tab,i) in currentTabs" :key="tab" :class="{active:activeTab===i}" @click="activeTab=i">{{tab}}<span v-if="currentTabCounts[i] !== '' && currentTabCounts[i] !== undefined">{{formatCount(currentTabCounts[i])}}</span></button></div>
<div class="module-layout"><article class="surface module-table-card"><div class="module-toolbar"><label class="module-search"><Search :size="16"/><input v-model="query" :placeholder="config.searchPlaceholder"/></label><div v-if="isOrders" class="filter-group order-filters"><ToolbarSelect v-model="channel" label="渠道" :options="channelOptions" aria-label="订单渠道"/><label><span>店铺 ID</span><input v-model="storeId" inputmode="numeric" placeholder="全部店铺"/></label><button class="button secondary icon-only" aria-label="刷新订单" @click="loadOrders"><RefreshCw :size="16"/></button></div><div v-else class="filter-group"><DateRangePicker v-if="title==='数据报表'" v-model="reportDates" @change="changeReportDates"/><ToolbarSelect v-for="f in (title==='数据报表'?config.filters.slice(1):config.filters)" :key="f" :model-value="filterValues[f]||f" :options="toolbarOptions(f)" :aria-label="f" @update:model-value="changeToolbarFilter(f,$event)"/></div></div>
<div v-if="selected.length" class="batch-bar"><strong>已选择 {{selected.length}} 项</strong><button>批量更新状态</button><button>批量导出</button><button @click="selected=[]">取消选择</button></div>
<TableState v-if="loading" state="loading" title="正在加载订单" description="正在从后台同步最新订单与履约状态。"/><TableState v-else-if="loadError" state="error" title="订单加载失败" :description="loadError"><template #action><button class="button secondary" @click="loadOrders">重新加载</button></template></TableState><TableState v-else-if="!rows.length" state="empty" :filtered="Boolean(query||channel||storeId||activeTab)" :title="isOrders?'没有找到订单':`没有找到${title}记录`" :description="isOrders?'当前条件下没有订单，调整筛选条件或清除搜索后再试。':'当前条件下没有业务记录，调整搜索或页签后再试。'"><template #action><button v-if="query||channel||storeId||activeTab" class="button secondary" @click="query='';channel='';storeId='';activeTab=0">清除筛选</button></template></TableState>
<div v-else class="table-scroll"><table class="module-table"><thead><tr><th class="check-cell"><input type="checkbox" :checked="allSelected" @change="toggleAll"/></th><th v-for="c in config.columns" :key="c">{{c}}</th><th class="action-cell">操作</th></tr></thead><tbody><tr v-for="(row,ri) in rows" :key="isOrders?remoteOrders[ri].id:ri" :class="{selected:selectedRow===ri}" @click="isOrders?selectOrder(ri):selectedRow=ri"><td class="check-cell"><input v-model="selected" type="checkbox" :value="ri" @click.stop/></td><td v-for="(cell,i) in row" :key="i" :class="{mono:i===0,'strong-cell':i===1}"><span v-if="i===config.statusColumn" class="status-tag" :data-status="cell">{{cell}}</span><template v-else>{{i===7&&isOrders?formatTime(cell):cell}}</template></td><td class="action-cell"><button class="row-action" aria-label="查看详情" @click.stop="isOrders ? openOrder(remoteOrders[ri]) : router.push(workflow.detail)"><MoreHorizontal :size="16"/></button></td></tr></tbody></table></div>
<footer class="table-footer"><span>共 {{isOrders ? orderTotal : (moduleKey[title] ? moduleTotal : config.total)}} 条记录</span><div v-if="isOrders&&orderPages>1"><button :disabled="page===1" @click="goPage(page-1)">上一页</button><button v-for="number in visiblePages" :key="number" :class="{active:page===number}" @click="goPage(number)">{{number}}</button><button :disabled="page===orderPages" @click="goPage(page+1)">下一页</button></div><div v-else-if="!isOrders"><button class="active">1</button></div></footer></article>
<aside v-if="isOrders" class="surface context-panel order-context"><TableState v-if="detailLoading" state="loading" title="正在加载订单详情" description="支付与履约信息正在同步。"/><template v-else-if="contextOrder"><div class="context-heading"><span>ORDER DETAIL</span><h2>订单 {{contextOrder.order_no}}</h2><p>{{displayChannel(contextOrder.channel_type||'storefront')}} · {{formatTime(contextOrder.created_at)}} 创建</p></div><div class="context-score"><span>履约完成度</span><strong>{{fulfillmentProgress}}%</strong><i><b :style="{width:fulfillmentProgress+'%'}"></b></i></div><div class="context-list"><button v-for="it in contextItems" :key="it.title"><span :data-tone="it.tone"></span><div><strong>{{it.title}}</strong><small>{{it.meta}}</small></div><ArrowRight :size="15"/></button></div><button class="context-action" @click="openOrder(contextOrder)">查看完整订单<ArrowRight :size="15"/></button></template><TableState v-else state="empty" title="尚未选择订单" description="从左侧列表选择一条订单查看支付和履约详情。"/></aside><aside v-else class="surface context-panel"><div class="context-heading"><span>{{config.panelEyebrow}}</span><h2>{{config.panelTitle}}</h2><p>{{config.panelDescription}}</p></div><div class="context-score"><span>{{config.scoreLabel}}</span><strong>{{config.score}}</strong><i><b :style="{width:config.scoreWidth+'%'}"></b></i></div><div class="context-list"><button v-for="it in config.panelItems" :key="it.title"><span :data-tone="it.tone"></span><div><strong>{{it.title}}</strong><small>{{it.meta}}</small></div><ArrowRight :size="15"/></button></div><button class="context-action" @click="router.push(workflow.detail)">{{config.panelAction}}<ArrowRight :size="15"/></button></aside></div>
</section></template>
