<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { ArrowLeft, Check, ChevronDown, Eye, MoreHorizontal, Pencil, Plus, Search, Trash2, X } from 'lucide-vue-next'
import { secondaryConfigs } from '../data/secondaryConfigs'
import TableState from '../components/common/TableState.vue'

const props=defineProps<{type:string}>(); const config=computed(()=>secondaryConfigs[props.type]); const query=ref(''); const activeStage=ref('全部')
const localRows=ref<string[][]>([]); const drawer=ref(false); const mode=ref<'create'|'view'|'edit'>('view'); const form=ref<string[]>([]); const editingIndex=ref(-1); const deleteIndex=ref(-1); const toast=ref(''); const validationError=ref('')
watch(config,value=>{const cached=localStorage.getItem(`ebase:crud:${props.type}`);localRows.value=cached?JSON.parse(cached):value.rows.map(row=>[...row]);query.value='';activeStage.value='全部'},{immediate:true})
const rows=computed(()=>{const k=query.value.trim().toLowerCase();return k?localRows.value.filter(r=>r.some(v=>v.toLowerCase().includes(k))):localRows.value})
const drawerTitle=computed(()=>mode.value==='create'?`新增${config.value.title.replace('管理','')}`:mode.value==='edit'?'编辑记录':'记录详情')
function notify(message:string){toast.value=message;setTimeout(()=>toast.value='',1800)}
function persist(){localStorage.setItem(`ebase:crud:${props.type}`,JSON.stringify(localRows.value))}
function openCreate(){mode.value='create';editingIndex.value=-1;validationError.value='';form.value=config.value.columns.map((_,i)=>i===0?`NEW-${Date.now().toString().slice(-6)}`:i===config.value.columns.length-1?'草稿':'');drawer.value=true}
function openRow(row:string[],targetMode:'view'|'edit'){mode.value=targetMode;editingIndex.value=localRows.value.indexOf(row);validationError.value='';form.value=[...row];drawer.value=true}
function startEdit(){mode.value='edit'}
function save(){if(!form.value[0]?.trim()||!form.value[1]?.trim()){validationError.value=`${config.value.columns[0]}和${config.value.columns[1]}为必填项`;return}if(mode.value==='create'){localRows.value.unshift([...form.value]);notify('新增记录已保存')}else if(editingIndex.value>=0){localRows.value[editingIndex.value]=[...form.value];notify('修改已保存')}persist();drawer.value=false}
function askDelete(row:string[]){deleteIndex.value=localRows.value.indexOf(row)}
function confirmDelete(){if(deleteIndex.value>=0)localRows.value.splice(deleteIndex.value,1);persist();deleteIndex.value=-1;drawer.value=false;notify('记录已删除')}
</script>

<template><section v-if="config" class="secondary-page"><RouterLink to="/features" class="secondary-back"><ArrowLeft :size="16"/>返回功能地图</RouterLink><div class="page-heading"><div><span class="eyebrow">{{config.group}}</span><h1>{{config.title}}</h1><p>{{config.description}}</p></div><button class="button primary" @click="openCreate"><Plus :size="16"/>{{config.action}}</button></div><section class="metric-strip module-metrics"><article v-for="m in config.metrics" :key="m[0]" class="metric-item"><span>{{m[0]}}</span><strong>{{m[1]}}</strong><small><b>{{m[2]}}</b></small></article></section>
<div class="stage-grid"><article v-for="stage in config.stages" :key="stage.title" class="surface stage-card" :class="{active:activeStage===stage.title}" @click="activeStage=activeStage===stage.title?'全部':stage.title"><header><h2>{{stage.title}}</h2><span>{{stage.count}}</span></header><ul><li v-for="entry in stage.items" :key="entry"><i></i>{{entry}}<MoreHorizontal :size="14"/></li></ul></article></div>
<article class="surface secondary-table"><div class="module-toolbar"><label class="module-search"><Search :size="16"/><input v-model="query" placeholder="搜索当前功能数据"/></label><button class="button secondary">{{activeStage}}<ChevronDown :size="14"/></button></div><TableState v-if="!rows.length" state="empty" :filtered="Boolean(query || activeStage !== '全部')" title="没有匹配的数据" description="调整搜索关键词或阶段筛选，查看其他业务记录。"><template #action><button class="button secondary" @click="query='';activeStage='全部'">清除筛选</button></template></TableState><div v-else class="table-scroll"><table><thead><tr><th v-for="c in config.columns" :key="c">{{c}}</th><th class="crud-actions-heading">操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row[0]" @dblclick="openRow(row,'view')"><td v-for="(cell,i) in row" :key="i" :class="{mono:i===0,'strong-cell':i===1}"><span v-if="i===row.length-1" class="status-tag" :data-status="cell">{{cell}}</span><template v-else>{{cell}}</template></td><td class="crud-actions"><button title="查看" @click="openRow(row,'view')"><Eye :size="14"/></button><button title="编辑" @click="openRow(row,'edit')"><Pencil :size="14"/></button><button class="danger" title="删除" @click="askDelete(row)"><Trash2 :size="14"/></button></td></tr></tbody></table></div><footer class="table-footer"><span>当前 {{localRows.length}} 条记录</span><div><button class="active">1</button></div></footer></article>

<Teleport to="body"><div v-if="drawer" class="crud-overlay" @click.self="drawer=false"><aside class="crud-drawer"><header><div><span>{{mode.toUpperCase()}}</span><h2>{{drawerTitle}}</h2><p>{{config.group}} · {{config.title}}</p></div><button @click="drawer=false"><X :size="18"/></button></header><div class="crud-form"><div v-if="validationError" class="crud-error">{{validationError}}</div><label v-for="(column,index) in config.columns" :key="column"><span>{{column}} <b v-if="index<2">*</b></span><select v-if="index===config.columns.length-1&&mode!=='view'" v-model="form[index]"><option>{{form[index]}}</option><option>正常</option><option>草稿</option><option>待审核</option><option>已停用</option></select><input v-else v-model="form[index]" :readonly="mode==='view'" :class="{readonly:mode==='view',invalid:validationError&&index<2&&!form[index]}"/></label></div><footer><button v-if="mode==='view'" class="button secondary danger-text" @click="askDelete(localRows[editingIndex])"><Trash2 :size="14"/>删除</button><span></span><button class="button secondary" @click="drawer=false">取消</button><button v-if="mode==='view'" class="button primary" @click="startEdit"><Pencil :size="14"/>编辑</button><button v-else class="button primary" @click="save"><Check :size="14"/>保存</button></footer></aside></div>
<div v-if="deleteIndex>=0" class="confirm-overlay"><div class="confirm-dialog"><div class="confirm-icon"><Trash2 :size="20"/></div><h2>确认删除这条记录？</h2><p>删除后将从当前原型数据中移除，此操作无法撤销。</p><div><button class="button secondary" @click="deleteIndex=-1">取消</button><button class="button delete-button" @click="confirmDelete">确认删除</button></div></div></div><div v-if="toast" class="crud-toast"><Check :size="15"/>{{toast}}</div></Teleport>
</section></template>
