<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { Bell, Building2, Check, ChevronRight, CreditCard, FileClock, LockKeyhole, Save, Settings2, ShieldCheck, Store, Users, Warehouse } from 'lucide-vue-next'
import { useToast } from '../composables/useToast'
import { ApiError } from '../api/client'
import { getSystemSettings, saveSystemSettings } from '../api/settings'
import { useSystemBranding } from '../composables/useSystemBranding'

const router=useRouter(); const active=ref('company'); const saved=ref(false); const {success,error:showError}=useToast(); const {setSystemName}=useSystemBranding()
const sections=[{id:'company',label:'企业信息',icon:Building2},{id:'members',label:'成员与角色',icon:Users},{id:'channels',label:'店铺与渠道',icon:Store},{id:'warehouse',label:'仓库配置',icon:Warehouse},{id:'payment',label:'支付配置',icon:CreditCard},{id:'notifications',label:'消息通知',icon:Bell},{id:'security',label:'安全设置',icon:LockKeyhole},{id:'logs',label:'操作日志',icon:FileClock}]
const configs=reactive<Record<string,{title:string;description:string;groups:{title:string;description:string;fields:{label:string;value:string;type?:string;hint?:string}[]}[]}>>({
company:{title:'企业信息',description:'维护企业主体、品牌信息和默认经营配置。',groups:[{title:'企业资料',description:'用于后台展示、合同与业务单据。',fields:[{label:'企业名称',value:'上海清透商业有限公司'},{label:'企业简称',value:'EBASE'},{label:'统一社会信用代码',value:'91310000MA1FL8XK26'},{label:'所属行业',value:'零售 / 电商',type:'select'},{label:'企业地址',value:'上海市浦东新区世纪大道 100 号'},{label:'客服热线',value:'400-820-2026'}]},{title:'品牌与区域',description:'设置系统品牌和默认时区。',fields:[{label:'系统名称',value:'商业运营后台'},{label:'默认语言',value:'简体中文',type:'select'},{label:'默认时区',value:'Asia/Shanghai (UTC+8)',type:'select'},{label:'默认货币',value:'人民币 CNY',type:'select'}]}]},
members:{title:'成员与角色',description:'管理组织成员、角色权限和数据范围。',groups:[{title:'成员概览',description:'当前共 86 位成员，12 个角色。',fields:[{label:'默认新成员角色',value:'只读成员',type:'select'},{label:'邀请链接有效期',value:'7 天',type:'select'},{label:'离职成员数据',value:'自动转移给直属负责人',type:'select'},{label:'成员目录可见性',value:'所有成员可见',type:'select'}]},{title:'角色权限',description:'进入独立权限矩阵配置每个角色。',fields:[{label:'超级管理员',value:'3 位成员 · 全部权限'},{label:'运营主管',value:'12 位成员 · 18/20 项权限'},{label:'仓库主管',value:'8 位成员 · 供应链数据'},{label:'内容编辑',value:'16 位成员 · 内容数据'}]}]},
channels:{title:'店铺与渠道',description:'连接销售渠道并配置订单、商品和库存同步。',groups:[{title:'已连接渠道',description:'连接状态和最近同步时间。',fields:[{label:'天猫旗舰店',value:'正常 · 5 分钟前同步'},{label:'京东自营店',value:'正常 · 8 分钟前同步'},{label:'抖音商城',value:'正常 · 3 分钟前同步'},{label:'品牌小程序',value:'正常 · 实时同步'}]},{title:'同步策略',description:'控制跨渠道业务数据更新。',fields:[{label:'订单同步频率',value:'实时',type:'select'},{label:'库存同步频率',value:'每 5 分钟',type:'select'},{label:'商品价格同步',value:'需要人工确认',type:'select'},{label:'同步失败通知',value:'发送给渠道负责人',type:'select'}]}]},
warehouse:{title:'仓库配置',description:'设置默认仓库、分仓规则和库存策略。',groups:[{title:'分仓与履约',description:'控制订单自动分配逻辑。',fields:[{label:'默认发货仓',value:'华东一号仓',type:'select'},{label:'分仓策略',value:'距离优先，库存次之',type:'select'},{label:'拆单策略',value:'优先不拆单',type:'select'},{label:'缺货处理',value:'自动转其他仓',type:'select'}]},{title:'库存规则',description:'安全库存和锁定策略。',fields:[{label:'默认安全库存',value:'20 件'},{label:'订单库存锁定',value:'30 分钟',type:'select'},{label:'低库存提醒',value:'低于安全库存时提醒',type:'select'},{label:'盘点期间销售',value:'允许销售可用库存',type:'select'}]}]},
payment:{title:'支付配置',description:'配置支付渠道、退款策略和财务对账。',groups:[{title:'支付渠道',description:'管理消费者可用的支付方式。',fields:[{label:'支付宝',value:'已启用 · 商户号 2088****2846'},{label:'微信支付',value:'已启用 · 商户号 1900****1086'},{label:'京东支付',value:'仅京东渠道启用'},{label:'抖音支付',value:'仅抖音渠道启用'}]},{title:'退款与对账',description:'设置自动退款和账单同步。',fields:[{label:'小额自动退款',value:'500 元以下',type:'select'},{label:'退款审批层级',value:'金额分级审批',type:'select'},{label:'自动对账时间',value:'每日 03:00',type:'select'},{label:'差异提醒阈值',value:'10 元'}]}]},
notifications:{title:'消息通知',description:'配置系统事件、接收人和通知渠道。',groups:[{title:'业务通知',description:'选择需要主动通知的业务事件。',fields:[{label:'订单异常',value:'站内信 + 企业微信',type:'select'},{label:'低库存预警',value:'站内信 + 企业微信',type:'select'},{label:'退款待审批',value:'站内信',type:'select'},{label:'活动审批',value:'站内信 + 邮件',type:'select'}]},{title:'通知规则',description:'控制提醒聚合和免打扰。',fields:[{label:'通知聚合',value:'5 分钟内同类消息合并',type:'select'},{label:'免打扰时间',value:'22:00 – 08:00'},{label:'高优先级通知',value:'忽略免打扰',type:'select'},{label:'日报发送时间',value:'每日 09:00'}]}]},
security:{title:'安全设置',description:'保护账号、数据和高风险操作。',groups:[{title:'登录安全',description:'企业成员的身份验证策略。',fields:[{label:'双重验证',value:'管理员和财务角色强制开启',type:'select'},{label:'密码有效期',value:'90 天',type:'select'},{label:'登录失败锁定',value:'连续 5 次失败锁定 30 分钟',type:'select'},{label:'异地登录',value:'阻止并通知管理员',type:'select'}]},{title:'数据与操作安全',description:'高风险操作和数据访问控制。',fields:[{label:'敏感数据脱敏',value:'手机号、地址、证件号',type:'select'},{label:'批量导出审批',value:'超过 5,000 条需要审批',type:'select'},{label:'操作日志留存',value:'180 天',type:'select'},{label:'会话超时',value:'无操作 2 小时',type:'select'}]}]},
logs:{title:'操作日志',description:'查看系统配置和权限变更记录。',groups:[{title:'日志筛选',description:'按操作者、模块和风险等级检索。',fields:[{label:'时间范围',value:'近 7 天',type:'select'},{label:'操作模块',value:'全部模块',type:'select'},{label:'风险等级',value:'全部等级',type:'select'},{label:'操作结果',value:'全部结果',type:'select'}]},{title:'最近高风险操作',description:'需要管理员复核的关键操作。',fields:[{label:'今天 10:42 · 林知夏',value:'导出高价值用户 8,642 条'},{label:'今天 09:18 · 陈曦',value:'修改营销主管审批权限'},{label:'昨天 18:06 · 系统',value:'拦截异地登录 183.6.82.14'},{label:'昨天 16:32 · 周宁',value:'批量调整 286 个 SKU 库存'}]}]}
})
const current=computed(()=>configs[active.value])
const fieldKeyMap:Record<string,string>={
  '企业名称':'company_name','企业简称':'company_short_name','统一社会信用代码':'social_credit_code','所属行业':'industry','企业地址':'address','客服热线':'service_phone','系统名称':'system_name','默认语言':'default_locale','默认时区':'default_timezone','默认货币':'default_currency','默认新成员角色':'default_role','邀请链接有效期':'invite_expiry_days','离职成员数据':'offboarding_policy','成员目录可见性':'directory_visibility','订单同步频率':'order_sync_frequency','库存同步频率':'inventory_sync_frequency','商品价格同步':'price_sync_policy','同步失败通知':'sync_failure_notification','默认发货仓':'default_warehouse','分仓策略':'allocation_strategy','拆单策略':'split_order_policy','缺货处理':'stockout_policy','默认安全库存':'default_safety_stock','订单库存锁定':'stock_reservation_minutes','低库存提醒':'low_stock_notification','盘点期间销售':'stocktake_sales_policy','小额自动退款':'small_refund_limit','退款审批层级':'refund_approval_policy','自动对账时间':'reconciliation_time','差异提醒阈值':'reconciliation_alert_threshold','订单异常':'order_exception','低库存预警':'low_stock','退款待审批':'refund_approval','活动审批':'campaign_approval','通知聚合':'notification_digest','免打扰时间':'quiet_hours','高优先级通知':'high_priority_bypass','日报发送时间':'daily_report_time','双重验证':'mfa_policy','密码有效期':'password_expiry_days','登录失败锁定':'login_failure_policy','异地登录':'unusual_login_policy','敏感数据脱敏':'mask_sensitive_data','批量导出审批':'export_approval_threshold','操作日志留存':'operation_log_retention_days','会话超时':'session_timeout_hours',
}
const loading=ref(false); const loadError=ref(''); const saving=ref(false)
async function loadSettings(){if(active.value==='logs')return;loading.value=true;loadError.value='';try{const result=await getSystemSettings(active.value);configs[active.value].groups.forEach(group=>group.fields.forEach(field=>{const key=fieldKeyMap[field.label];if(key&&result.settings[key]!==undefined)field.value=String(result.settings[key])}))}catch(e){loadError.value=e instanceof ApiError?e.body.message:'设置加载失败'}finally{loading.value=false}}
async function save(){if(active.value==='logs'){success('操作日志为只读信息','请使用日志筛选查看记录');return}saving.value=true;try{const settings:Record<string,unknown>={};configs[active.value].groups.forEach(group=>group.fields.forEach(field=>{const key=fieldKeyMap[field.label];if(key)settings[key]=field.value}));await saveSystemSettings(active.value,settings);if(active.value==='company'&&settings.system_name)setSystemName(String(settings.system_name));document.title=String(settings.system_name||document.title);saved.value=true;success('系统设置已保存',current.value.title);setTimeout(()=>saved.value=false,2000)}catch(e){showError('系统设置保存失败',e instanceof ApiError?e.body.message:'请稍后重试')}finally{saving.value=false}}
watch(active,()=>{void loadSettings()});onMounted(()=>{void loadSettings()})
</script>

<template><section class="settings-page"><div class="page-heading"><div><span class="eyebrow">ADMINISTRATION · 系统配置</span><h1>权限与系统设置</h1><p>集中管理企业、渠道、支付、安全和组织权限。</p></div><div class="heading-actions"><span v-if="saved" class="saved-toast"><Check :size="14"/>设置已保存</span><button class="button primary" @click="save"><Save :size="16"/>保存全部更改</button></div></div>
<div class="settings-layout"><aside class="settings-nav surface"><button v-for="section in sections" :key="section.id" :class="{active:active===section.id}" @click="active=section.id"><component :is="section.icon" :size="17"/><span>{{section.label}}</span><ChevronRight :size="14"/></button></aside>
<main class="settings-content"><header class="settings-content-heading"><div><h2>{{current.title}}</h2><p>{{current.description}}</p></div><div v-if="active==='members'" class="heading-actions"><button class="button secondary" @click="router.push('/settings/members')"><Users :size="15"/>成员目录</button><button class="button secondary" @click="router.push('/settings/roles/operator')"><ShieldCheck :size="15"/>编辑角色权限</button></div></header><div v-if="loading" class="surface settings-group"><p>正在加载设置...</p></div><div v-else-if="loadError" class="surface settings-group"><p>{{loadError}}</p><button class="button secondary" @click="loadSettings">重试</button></div><template v-else><article v-for="group in current.groups" :key="group.title" class="surface settings-group"><header><div><h3>{{group.title}}</h3><p>{{group.description}}</p></div><Settings2 :size="18"/></header><div class="settings-fields"><label v-for="field in group.fields" :key="field.label"><span>{{field.label}}</span><select v-if="field.type==='select'" v-model="field.value"><option :value="field.value">{{field.value}}</option><option>其他选项</option></select><input v-else v-model="field.value" /></label></div></article></template></main></div></section></template>
