<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowLeft, Check, ChevronDown, Clock3, Save } from 'lucide-vue-next'
import FileUploader from '../components/forms/FileUploader.vue'
import { useToast } from '../composables/useToast'

const props=defineProps<{type:string}>(); const router=useRouter(); const saved=ref(false); const activeSection=ref(0); const {success}=useToast()
type Field={label:string;value:string;kind?:'input'|'select'|'textarea'|'switch';wide?:boolean}
type Flow={title:string;eyebrow:string;description:string;back:string;sections:string[];fields:Field[];summary:[string,string][];events:string[];action:string}
const flows:Record<string,Flow>={
order:{title:'订单详情',eyebrow:'ORDER #EB202609010846',description:'查看支付、商品、客户与履约全过程。',back:'/orders',sections:['订单概览','商品与支付','履约记录','售后与备注'],fields:[{label:'订单状态',value:'已付款 / 待揽收',kind:'select'},{label:'销售渠道',value:'天猫旗舰店',kind:'select'},{label:'客户姓名',value:'张玥'},{label:'联系电话',value:'138 2846 1086'},{label:'收货地址',value:'上海市浦东新区世纪大道 100 号',wide:true},{label:'订单备注',value:'工作日送达，请勿放驿站',kind:'textarea',wide:true}],summary:[['商品金额','¥1,899.00'],['优惠金额','-¥80.00'],['运费','¥0.00'],['实付金额','¥1,819.00']],events:['10:42 支付已确认 · 支付宝','10:48 华东一号仓接单','11:06 商品配货完成','等待顺丰速运揽收'],action:'保存订单变更'},
logistics:{title:'异常运单处理',eyebrow:'WAYBILL SF128604780',description:'定位异常原因并记录处理方案。',back:'/logistics',sections:['异常概览','收件信息','物流轨迹','处理记录'],fields:[{label:'异常类型',value:'地址信息异常',kind:'select'},{label:'处理优先级',value:'高',kind:'select'},{label:'收件人',value:'陈曦'},{label:'联系电话',value:'158 4201 8862'},{label:'修正后地址',value:'杭州市滨江区江南大道 588 号 2 栋 1802',wide:true},{label:'处理备注',value:'已电话确认门牌号，等待承运商更新',kind:'textarea',wide:true}],summary:[['承运商','顺丰速运'],['所属仓库','华东一号仓'],['超时时长','2 小时 18 分'],['预计送达','09-03 18:00']],events:['09:16 仓库完成出库','10:02 顺丰首次揽收失败','10:28 系统识别地址异常','11:06 客服已联系收件人'],action:'提交处理结果'},
product:{title:'新建商品',eyebrow:'PRODUCT CREATION',description:'创建商品资料并配置渠道销售属性。',back:'/products',sections:['基础信息','销售规格','媒体素材','平台发布','独立站发布'],fields:[{label:'商品名称',value:'Air X Pro 主动降噪耳机',wide:true},{label:'商品类目',value:'数码影音 / 耳机',kind:'select'},{label:'所属品牌',value:'EBASE Audio',kind:'select'},{label:'销售价格',value:'1599.00'},{label:'市场指导价',value:'1899.00'},{label:'商品卖点',value:'40 dB 深度降噪、30 小时续航、沉浸式空间音频',kind:'textarea',wide:true},{label:'商品描述',value:'Air X Pro 面向通勤、差旅和专注办公场景设计。自适应降噪系统会根据环境声实时调整强度，搭配柔软记忆耳罩与轻量化头梁，长时间佩戴依然舒适。支持多设备快速切换、高清通话和有线音频模式，充电 10 分钟即可连续播放约 5 小时。',kind:'textarea',wide:true}],summary:[['SPU 编号','自动生成'],['SKU 数量','4'],['资料完整度','86%'],['发布渠道','4 个待配置']],events:['基础资料已自动保存','独立站 SEO 完整度 82%','天猫属性映射完成 18/22','中国大陆站等待发布'],action:'保存并进入规格配置'},
inventory:{title:'补货计划',eyebrow:'RESTOCK PLAN · 智能建议',description:'根据销量、库存和到货周期生成采购计划。',back:'/inventory',sections:['补货清单','供应商','到货计划','审批记录'],fields:[{label:'计划名称',value:'9 月第一周低库存补货',wide:true},{label:'目标仓库',value:'华东一号仓',kind:'select'},{label:'供应商',value:'深圳智联供应链',kind:'select'},{label:'预计到货',value:'2026-09-08'},{label:'采购负责人',value:'周宁',kind:'select'},{label:'补货说明',value:'优先保障会员日活动商品库存',kind:'textarea',wide:true}],summary:[['补货 SKU','6'],['采购数量','486'],['采购金额','¥284,600'],['预计周转','32 天']],events:['机械键盘 K8 · 180 件','智能手表 Pro · 64 件','降噪耳机 Air X · 80 件','其他 3 个 SKU · 162 件'],action:'提交补货审批'},
user:{title:'用户画像',eyebrow:'CUSTOMER U-286420',description:'整合会员、交易、标签和触达记录。',back:'/users',sections:['用户概览','消费行为','标签人群','触达记录'],fields:[{label:'客户姓名',value:'张玥'},{label:'会员等级',value:'黑金会员',kind:'select'},{label:'手机号',value:'138 2846 1086'},{label:'注册渠道',value:'天猫旗舰店',kind:'select'},{label:'用户标签',value:'高复购、数码偏好、高客单',wide:true},{label:'运营备注',value:'优惠敏感度低，适合会员权益类触达',kind:'textarea',wide:true}],summary:[['累计消费','¥68,420'],['累计订单','28'],['客单价','¥2,443'],['价值评分','92 / 100']],events:['今天 10:42 购买 AirPods Pro 2','08-18 浏览智能手表 Pro 6 次','08-12 领取黑金会员权益','07-28 完成售后满意度评价'],action:'保存画像标签'},
content:{title:'新建内容',eyebrow:'CONTENT EDITOR',description:'创作内容并配置多渠道发布计划。',back:'/content',sections:['内容编辑','关联商品','发布渠道','排期与审核'],fields:[{label:'内容标题',value:'秋季通勤装备：效率与质感兼得',wide:true},{label:'内容类型',value:'图文',kind:'select'},{label:'内容作者',value:'林知夏',kind:'select'},{label:'关联商品',value:'Voyage 旅行箱、Air X 耳机',wide:true},{label:'摘要',value:'从通勤场景出发，介绍三款兼具设计与效率的秋季装备。',kind:'textarea',wide:true},{label:'发布状态',value:'草稿',kind:'select'}],summary:[['字数','1,286'],['关联商品','3'],['目标渠道','小红书 / 小程序'],['预计发布','09-03 10:00']],events:['封面图 1200×900 已上传','敏感词检测通过','商品价格信息已同步','等待内容主管审核'],action:'保存并提交审核'},
coupon:{title:'新建优惠券',eyebrow:'COUPON CREATION',description:'配置优惠规则、领取限制与投放人群。',back:'/coupons',sections:['基础规则','适用范围','领取限制','投放计划'],fields:[{label:'优惠券名称',value:'中秋会员专享满减券',wide:true},{label:'优惠券类型',value:'满减券',kind:'select'},{label:'使用门槛',value:'满 699 元'},{label:'优惠金额',value:'80 元'},{label:'发行总量',value:'20,000 张'},{label:'有效期',value:'2026-09-10 至 2026-09-20',wide:true}],summary:[['目标人群','金卡及以上会员'],['适用渠道','全渠道'],['预计成本','¥1,600,000'],['预估带动成交','¥8,420,000']],events:['同一用户限领 1 张','不可与其他满减券叠加','退款后优惠券不退回','活动开始前 24 小时提醒'],action:'保存并创建优惠券'},
marketing:{title:'新建营销活动',eyebrow:'CAMPAIGN CREATION',description:'规划活动机制、预算、渠道和审批流程。',back:'/marketing',sections:['活动信息','优惠机制','渠道与人群','预算审批'],fields:[{label:'活动名称',value:'9 月超级会员日',wide:true},{label:'活动类型',value:'会员日',kind:'select'},{label:'活动时间',value:'2026-09-15 00:00 至 2026-09-17 23:59',wide:true},{label:'活动预算',value:'¥280,000'},{label:'活动负责人',value:'陈曦',kind:'select'},{label:'活动说明',value:'面向高价值会员的全渠道专享活动',kind:'textarea',wide:true}],summary:[['目标成交','¥2,180,000'],['预估 ROI','7.8'],['目标用户','42,186'],['发布渠道','4']],events:['满 999 减 120','黑金会员额外 95 折','核心商品库存校验通过','等待财务预算审批'],action:'提交活动审批'},
report:{title:'经营分析详情',eyebrow:'BUSINESS ANALYTICS · 近 30 天',description:'拆解经营增长来源与风险项。',back:'/reports',sections:['核心趋势','渠道贡献','商品结构','用户结构'],fields:[{label:'分析周期',value:'2026-08-03 至 2026-09-01',kind:'select',wide:true},{label:'对比周期',value:'上一个 30 天',kind:'select'},{label:'数据粒度',value:'按日',kind:'select'},{label:'店铺范围',value:'全部店铺',kind:'select'},{label:'渠道范围',value:'全部渠道',kind:'select'}],summary:[['成交额','¥28,642,380'],['支付订单','184,620'],['毛利率','38.6%'],['复购率','32.4%']],events:['数码影音成交同比 +24.6%','抖音渠道退款率高于均值 1.8%','老客成交贡献提升至 38.2%','华东地区客单价下降 4.6%'],action:'导出完整分析'},
settings:{title:'角色权限编辑',eyebrow:'ROLE · 运营主管',description:'配置功能权限、审批权限与数据范围。',back:'/settings',sections:['角色信息','功能权限','数据权限','成员与日志'],fields:[{label:'角色名称',value:'运营主管'},{label:'角色状态',value:'启用',kind:'select'},{label:'角色描述',value:'负责日常经营、订单、商品和营销协同管理',kind:'textarea',wide:true},{label:'数据范围',value:'全部店铺 / 全部渠道',kind:'select',wide:true},{label:'成员数量',value:'12 人'},{label:'权限模板',value:'运营管理模板',kind:'select'}],summary:[['功能权限','18 / 20'],['审批权限','3'],['数据范围','全渠道'],['最近修改','今天 09:42']],events:['订单：查看 / 编辑 / 导出 / 审批','商品：查看 / 编辑 / 导出','用户与营销：查看 / 编辑 / 审批','报表：查看 / 导出'],action:'保存角色权限'}
}
const f=(label:string,value:string,kind:Field['kind']='input',wide=false):Field=>({label,value,kind,wide})
const extraSteps:Record<string,Field[][]>={
order:[[f('商品清单','AirPods Pro 2 × 1', 'textarea',true),f('支付方式','支付宝','select'),f('支付流水号','2026090128461086'),f('发票状态','未申请','select')],[f('发货仓库','华东一号仓','select'),f('承运商','顺丰速运','select'),f('运单号','SF128604821'),f('预计送达','2026-09-02 18:00'),f('物流备注','工作日送达，请勿放驿站','textarea',true)],[f('售后状态','无售后','select'),f('退款金额','¥0.00'),f('客服负责人','赵倩','select'),f('内部标签','高价值客户 / 关注履约'),f('内部备注','订单履约正常，无需额外处理。','textarea',true)]],
logistics:[[f('收件人','陈曦'),f('联系电话','158 4201 8862'),f('省市区','浙江省 / 杭州市 / 滨江区','select'),f('详细地址','江南大道 588 号 2 栋 1802','textarea',true)],[f('当前节点','地址异常待处理','select'),f('承运商','顺丰速运','select'),f('运单轨迹','09:16 出库\n10:02 揽收失败\n10:28 地址异常','textarea',true),f('预计送达','2026-09-03 18:00')],[f('处理方案','修正地址后重新派送','select'),f('处理负责人','周宁','select'),f('承诺完成时间','今天 14:00'),f('客户沟通结果','已电话确认门牌号，客户同意明日送达','textarea',true)]],
product:[[f('规格名称','颜色 / 型号'),f('SKU 数量','4'),f('规格明细','曜石黑 · ¥1,599 · 库存 80\n星云银 · ¥1,599 · 库存 64','textarea',true),f('价格策略','统一零售价','select')],[f('商品主图','已上传 5 张'),f('详情页素材','已上传 8 张'),f('视频素材','Air X Pro 30s.mp4'),f('素材说明','主图需保持 1:1 白底，视频比例 9:16','textarea',true)],[f('发布渠道','天猫 / 京东 / 抖音 / 小程序','select',true),f('渠道类目','数码影音 / 耳机','select'),f('渠道价格','跟随商品售价','select'),f('定时发布','2026-09-05 10:00')],[f('发布站点','中国大陆站','select'),f('独立站状态','草稿','select'),f('独立站标题','Air X Pro 主动降噪耳机｜轻盈舒适，沉浸聆听',undefined,true),f('URL Slug','air-x-pro-noise-cancelling-headphones'),f('独立站售价','¥1,599.00'),f('库存策略','共享华东一号仓可售库存','select'),f('SEO 标题','Air X Pro 主动降噪耳机 | EBASE',undefined,true),f('SEO 描述','40 dB 自适应降噪，30 小时续航与多设备快速切换，适合通勤、差旅和专注办公。','textarea',true),f('独立站商品描述','从城市通勤到长途旅行，Air X Pro 通过自适应降噪与符合人体工学的轻量结构，让音乐、通话与安静空间随时可得。包装内含耳机、便携收纳盒、USB-C 充电线及音频连接线。','textarea',true),f('定时发布','2026-09-08 10:00')]],
inventory:[[f('供应商','深圳智联供应链','select'),f('采购联系人','刘经理'),f('联系电话','138 6820 4421'),f('付款账期','月结 30 天','select'),f('供应商备注','核心供应商，优先安排生产。','textarea',true)],[f('目标仓库','华东一号仓','select'),f('预计发货','2026-09-05'),f('预计到货','2026-09-08'),f('运输方式','整车运输','select'),f('到货要求','分 SKU 打托，附质检报告。','textarea',true)],[f('审批流程','采购主管 → 财务 → 总经理','select',true),f('预算科目','商品采购预算','select'),f('紧急程度','高','select'),f('审批说明','会员日前完成入库，建议加急审批。','textarea',true)]],
user:[[f('近 90 天订单','12 单 / ¥18,642','textarea',true),f('偏好品类','数码影音 / 智能穿戴'),f('购买频率','每 21 天'),f('退款率','0.8%')],[f('用户标签','黑金会员 / 高复购 / 高客单','textarea',true),f('所属人群','高价值会员','select'),f('RFM 等级','R5 F4 M5','select'),f('生命周期','成熟期','select')],[f('最近触达','08-28 会员权益通知'),f('首选渠道','微信服务号','select'),f('可触达状态','允许营销触达','select'),f('跟进计划','会员日前发送专享权益提醒','textarea',true)]],
content:[[f('关联商品','Voyage 旅行箱 / Air X 耳机','select',true),f('商品卡样式','横向双商品卡','select'),f('价格展示','展示会员价','select'),f('转化目标','商品详情页','select')],[f('发布渠道','小红书 / 小程序','select',true),f('渠道封面','cover-commute.jpg'),f('小红书话题','#秋季通勤 #效率装备'),f('小程序栏目','精选内容','select')],[f('发布时间','2026-09-03 10:00'),f('审核人','内容主管 · 苏然','select'),f('审核优先级','普通','select'),f('审核备注','确认商品价格与活动时间一致。','textarea',true)]],
coupon:[[f('适用商品','全场商品','select',true),f('适用类目','全部类目','select'),f('适用渠道','全渠道','select'),f('排除商品','秒杀商品 / 预售商品','textarea',true)],[f('目标人群','金卡及以上会员','select',true),f('每人限领','1 张','select'),f('每日领取上限','5,000 张'),f('叠加规则','不可与其他满减券叠加','select'),f('退款返券','不退回','select')],[f('投放方式','人群包批量发放','select'),f('投放时间','2026-09-09 20:00'),f('触达渠道','站内信 / 微信服务号','select',true),f('消息模板','中秋会员专享优惠已到账','textarea',true),f('预算审批人','营销总监 · 林知夏','select')]],
marketing:[[f('优惠机制','满 999 减 120','select'),f('会员加码','黑金会员额外 95 折','select'),f('活动商品','核心商品 86 个','select',true),f('互斥规则','不与秒杀、预售活动叠加','textarea',true)],[f('目标人群','金卡及以上会员','select'),f('目标人数','42,186'),f('发布渠道','天猫 / 京东 / 抖音 / 小程序','select',true),f('触达组合','站内信 + 服务号 + 短信','select')],[f('活动预算','¥280,000'),f('预算科目','会员运营','select'),f('审批流程','营销总监 → 财务总监','select',true),f('ROI 目标','7.8'),f('风险说明','优惠成本率不超过 12%。','textarea',true)]],
report:[[f('渠道指标','成交额 / 订单 / 转化率','select',true),f('渠道范围','天猫 / 京东 / 抖音 / 小程序','select',true),f('排序方式','按成交额降序','select'),f('异常阈值','同比下降超过 10%')],[f('商品维度','一级类目 / 品牌 / SPU','select'),f('商品指标','成交额 / 毛利 / 库存周转','select',true),f('Top 数量','Top 20'),f('排除范围','已下架商品','select')],[f('用户维度','新老客 / 会员等级 / 地域','select'),f('用户指标','用户数 / 客单价 / 复购率','select',true),f('报表输出','在线报表 + Excel','select'),f('订阅频率','每周一 08:00','select')]],
settings:[[f('订单权限','查看 / 编辑 / 导出 / 审批','select',true),f('商品权限','查看 / 编辑 / 导出','select',true),f('用户权限','查看 / 编辑','select',true),f('营销权限','查看 / 编辑 / 审批','select',true)],[f('店铺范围','全部店铺','select'),f('渠道范围','全部渠道','select'),f('仓库范围','华东 / 华南仓','select'),f('用户数据脱敏','手机号与地址脱敏','select',true)],[f('角色成员','林知夏、陈曦等 12 人','textarea',true),f('权限生效时间','保存后立即生效','select'),f('变更通知','通知所有角色成员','select'),f('变更原因','根据新组织架构调整运营权限。','textarea',true)]]
}
const flow=computed(()=>flows[props.type]); const activeFields=computed(()=>activeSection.value===0?flow.value.fields:extraSteps[props.type][activeSection.value-1]); const isLast=computed(()=>activeSection.value===flow.value.sections.length-1); const formValues=reactive<Record<string,string>>({}); const fieldKey=(field:Field)=>`${activeSection.value}-${field.label}`
watch(activeFields,fields=>fields.forEach(field=>{const key=fieldKey(field);if(!(key in formValues))formValues[key]=field.value}),{immediate:true})
function save(message='修改已保存'){saved.value=true;success(message,`${flow.value.title} · ${flow.value.sections[activeSection.value]}`);setTimeout(()=>saved.value=false,2200)} function saveDraft(){save('草稿已保存')} function next(){save(isLast.value?'流程已完成':'当前步骤已保存');if(!isLast.value)activeSection.value++} function previous(){save('当前步骤已保存');if(activeSection.value>0)activeSection.value--}
</script>

<template><section class="workflow-page"><div class="workflow-top"><button class="back-button" @click="router.push(flow.back)"><ArrowLeft :size="17"/>返回</button><div class="workflow-actions"><span v-if="saved" class="saved-toast"><Check :size="14"/>已保存</span><button class="button secondary" @click="saveDraft">保存草稿</button><button class="button primary" @click="save()"><Save :size="15"/>{{flow.action}}</button></div></div>
<div class="workflow-heading"><span class="eyebrow">{{flow.eyebrow}}</span><h1>{{flow.title}}</h1><p>{{flow.description}}</p></div><div class="workflow-tabs"><button v-for="(s,i) in flow.sections" :key="s" :class="{active:activeSection===i}" @click="activeSection=i"><span>{{i+1}}</span>{{s}}</button></div>
<div class="workflow-layout"><div class="workflow-main"><article class="surface form-card"><header><h2>{{flow.sections[activeSection]}}</h2><p>填写并确认当前步骤所需的业务信息。</p></header><div class="form-grid"><label v-for="field in activeFields" :key="field.label" :class="{wide:field.wide}"><span>{{field.label}}</span><textarea v-if="field.kind==='textarea'" v-model="formValues[fieldKey(field)]" class="textarea-control"></textarea><select v-else-if="field.kind==='select'" v-model="formValues[fieldKey(field)]" class="field-control"><option :value="field.value">{{field.value}}</option><option>其他选项</option></select><input v-else v-model="formValues[fieldKey(field)]" class="field-control"/></label></div><footer class="step-actions"><button class="button secondary" :disabled="activeSection===0" @click="previous">上一步</button><span>步骤 {{activeSection+1}} / {{flow.sections.length}}</span><button class="button primary" @click="next">{{isLast?'完成并保存':'下一步'}}</button></footer></article>
<article class="surface upload-card upload-card-complete"><header><h3>{{type==='product'?'商品图片与媒体素材':'附件与业务凭证'}}</h3><p>{{type==='product'?'默认素材用于版式预览，上传正式图片后可替换。':'上传合同、凭证、商品素材或业务表格。'}}</p></header><div v-if="type==='product'" class="product-placeholder-gallery"><figure v-for="image in [{src:'/placeholders/air-x-front.svg',label:'商品主图'},{src:'/placeholders/air-x-side.svg',label:'侧面细节'},{src:'/placeholders/air-x-scene.svg',label:'通勤场景'},{src:'/placeholders/air-x-package.svg',label:'包装展示'}]" :key="image.src"><img :src="image.src" :alt="`Air X Pro ${image.label}占位图`"/><figcaption><strong>{{image.label}}</strong><span>占位素材</span></figcaption></figure></div><FileUploader /></article></div>
<aside class="workflow-aside"><article class="surface summary-card"><h2>信息摘要</h2><dl><div v-for="row in flow.summary" :key="row[0]"><dt>{{row[0]}}</dt><dd>{{row[1]}}</dd></div></dl></article><article class="surface timeline-card"><h2>记录与提示</h2><ol><li v-for="event in flow.events" :key="event"><span></span><p>{{event}}</p></li></ol><div class="autosave"><Clock3 :size="14"/>所有修改将自动保存</div></article></aside></div></section></template>
